language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
services:
- mysql
before_script:
- mysql --user=root --execute='CREATE DATABASE IF NOT EXISTS test;'
- mysql --user=root --execute='GRANT ALL ON test.* TO test@localhost;'
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: nKPc7A2yVFgoq9xbA0EnlQWMAZxqqqi/bFLMXzayYN6c4HX/lWbVL+qTVRa5rdLBl72qOL0lWKMqiFHGrO+loXbIlcEL/OWll0CuO8yBzvv9HJ7aRDsb9vaNnyJiywh4fUI/Dbh5HXFvk7xuyfiQ2hPb1lfhEQe/lWa+8yfNCUc=
notifications:
  email: false
  slack:
    secure: a5NyyYQ20pG7Qr6qYBtte83eIqc5bn58oMV0+sGZSqcVEobQBz5l00MolyUPy8Uz6bOxCpdh1a9P9yNxqRTpdcXpfgVAitk0dixhW1y9ajSEo7ItmbphRQqWwROPh0zRbWlje6B5jwLziw9c1m+Ih7dgYB3gim3WlV1SaJvHkDo=
sudo: false
