language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: J/ImjMDjenwPUXB8IrFfCyhGNJw85IxMECqI17aROT98T0l2SJmUwui2QT7TF6iRCZyZCnW7UB3/nc9vYDBzcfotbQ3RYfaixkk8fjJwbyPZZ02XykuBXx5QHuDWSNBOIQshD4F6idE3zxgl5kcZ/Kzxifpvo7lU9nY4ArI1Glk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: a5NyyYQ20pG7Qr6qYBtte83eIqc5bn58oMV0+sGZSqcVEobQBz5l00MolyUPy8Uz6bOxCpdh1a9P9yNxqRTpdcXpfgVAitk0dixhW1y9ajSEo7ItmbphRQqWwROPh0zRbWlje6B5jwLziw9c1m+Ih7dgYB3gim3WlV1SaJvHkDo=
sudo: false
